### ISSUE TITLE
请问如果我想训练自己的数据，需要怎么更改.cfg文件？

### ISSUE THREAD

**Issue by JimXu1989** [dog-qiuqiu/Yolo-Fastest#17]
您好！

如果我想训练自己的数据集，需要如何更改.cfg文件？我看这个项目中的.cfg文件格式和darknet yolov4的还是不太一样，比如我的classes数量和预训练的模型不一样，我需要按什么规则更改呢？

**Comment by undefinedcodezhong** [comment]
这个cfg是类似yolov3的配置，修改classes， 然后每个[yolo]层的前一层卷积核数量（filters）改为（classes+1）* 3

**Comment by zxj11838** [comment]
You can refer to this part of （How to train ）the project（https://github.com/AlexeyAB/darknet）.

**Comment by Lebhoryi** [comment]
> You can refer to this part of （How to train ）the project（[https://github.com/AlexeyAB/darknet）](https://github.com/AlexeyAB/darknet%EF%BC%89).

sry, the link is invalid now

**Comment by zxj11838** [comment]
@Lebhoryi   Copy the URL and enter it into the browser.

**Comment by Lebhoryi** [comment]
@zxj11838 It works now. 

There is a new question, how could I convert model to '.h5' model successfully?

**Comment by zxj11838** [comment]
Sorry, I have not converted.
