### ISSUE TITLE
About ncnn_sample Compile Guide

### ISSUE THREAD

**Issue by Hideousmon** [dog-qiuqiu/Yolo-Fastest#25]
Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.

**Comment by 2684160504** [comment]
> Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.

HI,* g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp
* Usage: ./yolo-fastest:
how to use?

**Comment by Hideousmon** [comment]
> > Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.
> 
> HI,* g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp
> 
> * Usage: ./yolo-fastest:
>   how to use?

If there is no errors while compiling, you should be able to simply run ./yolo-fastest in the dir.

**Comment by 2684160504** [comment]
> > > Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.
> > 
> > 
> > HI,* g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp
> > 
> > * Usage: ./yolo-fastest:
> >   how to use?
> 
> If there is no errors while compiling, you should be able to simply run ./yolo-fastest in the dir.

![Screenshot from 2020-10-20 14-59-52](https://user-images.githubusercontent.com/44891815/96551623-2acfbc00-12e5-11eb-9e63-19e16f53f843.png)
After compiling NCNN,run Yolo-fastest?

**Comment by Hideousmon** [comment]
> > > > Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.
> > > 
> > > 
> > > HI,* g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp
> > > 
> > > * Usage: ./yolo-fastest:
> > >   how to use?
> > 
> > 
> > If there is no errors while compiling, you should be able to simply run ./yolo-fastest in the dir.
> 
> ![Screenshot from 2020-10-20 14-59-52](https://user-images.githubusercontent.com/44891815/96551623-2acfbc00-12e5-11eb-9e63-19e16f53f843.png)
> After compiling NCNN,run Yolo-fastest?


1. complie ncnn.
2. copy NCNN's 'lib' and 'include' (in the dir 'ncnn->build->install' after successfully compiling ncnn ) into the dir 'ncnn_sample'.
3. run the instruction to compile: 
`g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp`
and if you use OPENCV 4.X, it should be:
`g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv4` -fopenmp`
4. run
`./yolo-fastest`

Hope helpful.

**Comment by 2684160504** [comment]
Thanks very much！



---Original---

**Comment by 2684160504** [comment]
> Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.

Hi,how do the other files work in yolofastestmaster?Such as darknet_image.py.I,m looking forward to your reply,thank you.

**Comment by Hideousmon** [comment]
> > Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.
> 
> Hi,how do the other files work in yolofastestmaster?Such as darknet_image.py.I,m looking forward to your reply,thank you.

I haven't tried to run darknet_image.py. 😂 You can refer to the the usage in yolov3, maybe.

**Comment by 2684160504** [comment]
> > > Sincerely suggest that you could add “\” before the “`” in ncnn_sample's README.md, so that it may be easier for new comers to get started.
> > 
> > 
> > Hi,how do the other files work in yolofastestmaster?Such as darknet_image.py.I,m looking forward to your reply,thank you.
> 
> I haven't tried to run darknet_image.py. joy You can refer to the the usage in yolov3, maybe.

Thanks a lot,I will try it.

**Comment by wwdok** [comment]
> 1. complie ncnn.
> 2. copy NCNN's 'lib' and 'include' (in the dir 'ncnn->build->install' after successfully compiling ncnn ) into the dir 'ncnn_sample'.
> 3. run the instruction to compile:
>    `` g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp ``
>    and if you use OPENCV 4.X, it should be:
>    `` g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv4` -fopenmp ``
> 4. run
>    `./yolo-fastest`
> 
> Hope helpful.

Hi, @Hideousmon Could you let me see your contents in `ncnn\build\install\lib`
my lib folder seems not include `libncnn.a`:
![image](https://user-images.githubusercontent.com/43233772/99895605-0e4be880-2cc4-11eb-95b9-406d31ebe969.png)

**Comment by Hideousmon** [comment]
![image](https://user-images.githubusercontent.com/43981919/99943213-e59f1e00-2dab-11eb-918a-0ea05e94093e.png)

It's on Ubunutu 18.04 Mate. I didn't have a try on Windows.

> > 1. complie ncnn.
> > 2. copy NCNN's 'lib' and 'include' (in the dir 'ncnn->build->install' after successfully compiling ncnn ) into the dir 'ncnn_sample'.
> > 3. run the instruction to compile:
> >    `` g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv` -fopenmp ``
> >    and if you use OPENCV 4.X, it should be:
> >    `` g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn/ lib/libncnn.a `pkg-config --libs --cflags opencv4` -fopenmp ``
> > 4. run
> >    `./yolo-fastest`
> > 
> > Hope helpful.
> 
> Hi, @Hideousmon Could you let me see your contents in `ncnn\build\install\lib`
> my lib folder seems not include `libncnn.a`:
> ![image](https://user-images.githubusercontent.com/43233772/99895605-0e4be880-2cc4-11eb-95b9-406d31ebe969.png)

**Comment by jiangjiaxiaotianxia** [comment]
anyone who know how to compile this demo in window?

**Comment by jiangjiaxiaotianxia** [comment]
@2684160504 @Hideousmon

**Comment by Hideousmon** [comment]
> anyone who know how to compile this demo in window?

I did not try that.:sweat: It should be similar to compiling the other C++ programs on Windows but include ncnn's libs since ncnn is supported on Windows.

**Comment by jiangjiaxiaotianxia** [comment]
my instruction  in the  ncnn sample dir in cmd: g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn lib/ncnn.lib 'pkg-config --libs --cflags opencv' -fopenmp
mistake:
g++: error: 'pkg-config: No such file or directory
g++: error: opencv': No such file or directory
g++: error: unrecognized command line option '--libs'
g++: error: unrecognized command line option '--cflags'

**Comment by jiangjiaxiaotianxia** [comment]
my instruction :g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn lib/ncnn.lib `pkg-config --libs --cflags opencv` -fopenmp
still  this mistake
g++: error: `pkg-config: No such file or directory
g++: error: opencv`: No such file or directory
g++: error: unrecognized command line option '--libs'
g++: error: unrecognized command line option '--cflags'

**Comment by jiangjiaxiaotianxia** [comment]
instruction :g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn lib/ncnn.lib `pkg-config --libs --cflags opencv`  -fopenmp
still this mistake:
g++: error: `pkg-config: No such file or directory
g++: error: opencv`: No such file or directory
g++: error: unrecognized command line option '--libs'
g++: error: unrecognized command line option '--cflags'

**Comment by CW-B-W** [comment]
> instruction :g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn lib/ncnn.lib `pkg-config --libs --cflags opencv` -fopenmp
> still this mistake:
> g++: error: `pkg-config: No such file or directory g++: error: opencv`: No such file or directory
> g++: error: unrecognized command line option '--libs'
> g++: error: unrecognized command line option '--cflags'

I didn't try this on Windows
But I think you may try to replace \`pkg-config --libs --cflags\` with the `-L -I` options.

For example in [OpenCV C++ installation on Windows with MinGW](https://medium.com/csmadeeasy/opencv-c-installation-on-windows-with-mingw-c0fc1499f39) Step 5, 

```
$ g++ -I"C:\opencv\install\include" -L"C:\opencv\install\x64\mingw\lib" -L"C:\opencv\install\x64\mingw\bin"  opencvtry.cpp -lopencv_core420 -lopencv_highgui420 -lopencv_imgproc420 -lopencv_imgcodecs420 -o app
```
Replace the above path with your opencv installation path.

The `-I` option tell g++ where to search the opencv header files, the `-L` option tell g++ where to search the opencv libs.

**Comment by jiangjiaxiaotianxia** [comment]
@Hideousmon @CW-B-W 

my instruction  in the ncnn sample dir in cmd:g++ -o yolo-fastest yolo-fastest.cpp -I"D:\Yolo-fastest-github\Yolo-Fastest-master\ncnn_sample\include\ncnn" -L"D:\Yolo-fastest-github\Yolo-Fastest-master\ncnn_sample\lib/ncnn.lib" -L"D:\opencv3.4.1\opencv\build\x64\vc14\lib" -I"D:\opencv3.4.1\opencv\build\include" -fopenmp

I try it and still meet the question on the next:

 C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x141): undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int, ncnn::Allocator*)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x1ad): undefined reference to `ncnn::Mat::substract_mean_normalize(float const*, float const*)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x1c3): undefined reference to `ncnn::Net::create_extractor() const'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x1e4): undefined reference to `ncnn::Extractor::set_num_threads(int)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x205): undefined reference to `ncnn::Extractor::input(char const*, ncnn::Mat const&)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x245): undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&, int)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x451): undefined reference to `cv::rectangle(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x504): undefined reference to `cv::getTextSize(cv::String const&, int, double, int, int*)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x5fc): undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x665): undefined reference to `ncnn::Extractor::~Extractor()'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x776): undefined reference to `ncnn::Extractor::~Extractor()'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x882): undefined reference to `ncnn::Net::Net()'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x8a0): undefined reference to `ncnn::Net::load_param(char const*)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x8b7): undefined reference to `ncnn::Net::load_model(char const*)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x8f0): undefined reference to `cv::VideoCapture::VideoCapture(int)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x8f8): undefined reference to `cv::VideoCapture::operator>>(cv::Mat&)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x91a): undefined reference to `ncnn::get_current_time()'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x948): undefined reference to `ncnn::get_current_time()'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x9b7): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0x9eb): undefined reference to `cv::waitKey(int)'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0xa50): undefined reference to `cv::VideoCapture::~VideoCapture()'
C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o:yolo-fastest.cpp:(.text+0xae2): undefined reference to `ncnn::Net::~Net()'
d:/pkg-config-for-g++/windows--build/bin/../lib/gcc/i686-w64-mingw32/4.8.3/../../../../i686-w64-mingw32/bin/ld.exe: C:\Users\~1\AppData\Local\Temp\ccNA9Hda.o: bad reloc address 0x0 in section `.data'
d:/pkg-config-for-g++/windows--build/bin/../lib/gcc/i686-w64-mingw32/4.8.3/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status


> > instruction :g++ -o yolo-fastest yolo-fastest.cpp -I include/ncnn lib/ncnn.lib `pkg-config --libs --cflags opencv` -fopenmp
> > still this mistake:
> > g++: error: `pkg-config: No such file or directory g++: error: opencv`: No such file or directory
> > g++: error: unrecognized command line option '--libs'
> > g++: error: unrecognized command line option '--cflags'
> 
> On linux, it should work if ncnn and opencv are well installed. CW-B-W's reply seems quite helpful for compling the demo on Windows.

**Comment by jiangjiaxiaotianxia** [comment]
I install the pkg-config and window--build,but still questions
I decide to give up .Thank you very much for helping me .
