### ISSUE TITLE
Can’t use GPU for training or testing

### ISSUE THREAD

**Issue by chenmingguo** [dog-qiuqiu/Yolo-Fastest#35]
I used CUDA 10.2，cudnn 7.6.5，GPU NVIDIA GeForce RTX 2060

I have set up in Makefile 
GPU=1
CUDNN=1
ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda-10.2/include/
CFLAGS+= -DGPU
LDFLAGS+= -L/usr/local/cuda-10.2/lib64 -lcuda -lcudart -lcublas -lcurand

 C:\Yolo-Fastest\build\darknet\x64>  ./darknet.exe detector test ./cfg/voc.data ./cfg/yolo-fastest.cfg ./cfg/yolo-fastest.weights ./data/person.jpg -i 1 -thresh 0.25 -out_filename ./data/person_output.jpg

CUDA status Error: file: c:\yolo-fastest\src\dark_cuda.c : cuda_set_device() : line: 39 : build time: Nov 24 2020 - 18:36:35
CUDA Error: invalid device ordinal

Can anyone help to fix this?

**Comment by chenmingguo** [comment]
I have resolved

**Comment by abigail12138** [comment]
how did you fix the problem?thx
