### ISSUE TITLE
How to get the pre-trained weights for yolo-fastest-xl ?

### ISSUE THREAD

**Issue by arnoldfychen** [dog-qiuqiu/Yolo-Fastest#5]
Hello qiuqiu,

Is my understanding below right ?  
The commands for getting the pre-trained weights for yolo-fastest-xl and training yolo-fastest-xl are :

./darknet partial yolo-fastest-xl.cfg yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
./darknet detector train voc.data yolo-fastest-xl.cfg yolo-fastest-xl.conv.109

Thanks.

**Comment by monoloxo** [comment]
./darknet partial yolo-fastest-xl.cfg yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
这条命令就可以得到pre-trained weights文件了，就是 yolo-fastest-xl.conv.109 ，后面那一条是在这个基础上的训练

**Comment by arnoldfychen** [comment]
OK,  thanks, you can close this issue.

**Comment by ShidiDaisy** [comment]
> ./darknet partial yolo-fastest-xl.cfg yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
> 这条命令就可以得到pre-trained weights文件了，就是 yolo-fastest-xl.conv.109 ，后面那一条是在这个基础上的训练

你好，我在project root directory 下run的
./darknet partial yolo-fastest-xl.cfg yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
但是output
```
 CUDA-version: 10010 (11000), cuDNN: 7.6.5, GPU count: 1  
 OpenCV version: 3.3.1
Couldn't open file: yolo-fastest-xl.cfg
```
请问是怎么回事呢

**Comment by MuhammadAsadJaved** [comment]
@ShidiDaisy 

The weights and cfg are placeD in Yolo-Fastest/COCO/   folder for coco ,  and Yolo-Fastest/VOC/  folder for the voc.  You need to give the path for the relevent files.

For coco try this. 

./darknet partial Yolo-Fastest/COCO/yolo-fastest-xl.cfg  Yolo-Fastest/COCO/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109

For voc try this 
./darknet partial Yolo-Fastest/VOC/yolo-fastest-xl.cfg  Yolo-Fastest/VOC/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109

**Comment by MuhammadAsadJaved** [comment]
> @ShidiDaisy
> 
> The weights and cfg are placeD in Yolo-Fastest/COCO/ folder for coco , and Yolo-Fastest/VOC/ folder for the voc. You need to give the path for the relevent files.
> 
> For coco try this.
> 
> ./darknet partial Yolo-Fastest/COCO/yolo-fastest-xl.cfg Yolo-Fastest/COCO/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
> 
> For voc try this
> ./darknet partial Yolo-Fastest/VOC/yolo-fastest-xl.cfg Yolo-Fastest/VOC/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109

@ShidiDaisy 

如果您使用的是最新提交。 如果您使用的是旧项目，请使用此项目。

./darknet partial Yolo-Fastest/yolo-fastest-xl.cfg Yolo-Fastest/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109

**Comment by ShidiDaisy** [comment]
> @ShidiDaisy
> 
> The weights and cfg are placeD in Yolo-Fastest/COCO/ folder for coco , and Yolo-Fastest/VOC/ folder for the voc. You need to give the path for the relevent files.
> 
> For coco try this.
> 
> ./darknet partial Yolo-Fastest/COCO/yolo-fastest-xl.cfg Yolo-Fastest/COCO/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
> 
> For voc try this
> ./darknet partial Yolo-Fastest/VOC/yolo-fastest-xl.cfg Yolo-Fastest/VOC/yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109

I see! Thanks for your information.

**Comment by csqqlee** [comment]
你好,请问为什么抽取的是109层呢,能告诉我109层都是指的哪部分的吗?

**Comment by 2684160504** [comment]
> Hello qiuqiu,
> 
> Is my understanding below right ?
> The commands for getting the pre-trained weights for yolo-fastest-xl and training yolo-fastest-xl are :
> 
> ./darknet partial yolo-fastest-xl.cfg yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
> ./darknet detector train voc.data yolo-fastest-xl.cfg yolo-fastest-xl.conv.109
> 
> Thanks.

Hi,How to test and train on weight and cfg of yolo-fastest?I,m a newer and hope that I get your help.Thank you

**Comment by MuhammadAsadJaved** [comment]
> > Hello qiuqiu,
> > Is my understanding below right ?
> > The commands for getting the pre-trained weights for yolo-fastest-xl and training yolo-fastest-xl are :
> > ./darknet partial yolo-fastest-xl.cfg yolo-fastest-xl.weights yolo-fastest-xl.conv.109 109
> > ./darknet detector train voc.data yolo-fastest-xl.cfg yolo-fastest-xl.conv.109
> > Thanks.
> 
> Hi,How to test and train on weight and cfg of yolo-fastest?I,m a newer and hope that I get your help.Thank you

For training, you can use another [project](https://github.com/AlexeyAB/darknet). https://github.com/dog-qiuqiu/Yolo-Fastest#train
