### ISSUE TITLE
请问到哪里找yolo-fastest.conv.109？

### ISSUE THREAD

**Issue by JimXu1989** [dog-qiuqiu/Yolo-Fastest#9]
感谢您的技术分享！！
请问预训练weights yolo-fastest.conv.109要到哪里下载呢？
多谢！

**Comment by dog-qiuqiu** [comment]
需要用我提供的weights生成conv，readme有说明哦

**Comment by JimXu1989** [comment]
> 需要用我提供的weights生成conv，readme有说明哦

谢谢！问题已解决

**Comment by csqqlee** [comment]
你好,请问为什么抽取的是109层呢,能告诉我109层都是指的哪部分的吗?

**Comment by meanmee** [comment]
你提供的weights不是在COCO上训练了的吗，那我再用来训练有什么意义呢？ @dog-qiuqiu

**Comment by DESXIE** [comment]
> 感谢您的技术分享！！
> 请问预训练weights yolo-fastest.conv.109要到哪里下载呢？
> 多谢！

你好，我也遇到了相同的问题，在输入  "./darknet partial yolo-fastest.cfg yolo-fastest.weights yolo-fastest.conv.109 109" 时，显示"Couldn't open file: yolo-fastest.cfg"，在根目录下 ls  后也没有看见相关文件，应该怎么解决呢？

**Comment by juniorWu96** [comment]
> 你提供的weights不是在COCO上训练了的吗，那我再用来训练有什么意义呢？ @dog-qiuqiu

没意思，所以不要弄了

**Comment by juniorWu96** [comment]
> > 感谢您的技术分享！！
> > 请问预训练weights yolo-fastest.conv.109要到哪里下载呢？
> > 多谢！
> 
> 你好，我也遇到了相同的问题，在输入 "./darknet partial yolo-fastest.cfg yolo-fastest.weights yolo-fastest.conv.109 109" 时，显示"Couldn't open file: yolo-fastest.cfg"，在根目录下 ls 后也没有看见相关文件，应该怎么解决呢？

正是因为没有config文件才会报错，没有文件就自己创建一个。从他项目路径下把*.1.1.cfg拷过来，修改下batch_size和yolo层啥的，就行了。

**Comment by DESXIE** [comment]
@juniorWu96 已经解决啦~不过还是谢谢您！
